using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InventoryManagementSystem
{
    class Constants
    {
        public const string SIGNIN_INFO = "SignInForm";
        public const string SIGNUP_INFO = "SignUpForm";
        public const string UPDATE_ITEM_FORM = "UpdateItemForm";
        public const string INVENTORYSTORE_FORM = "InventoryStoreForm";
        public const string ADD_ITEM_FORM = "AddItemsForm";
        public const string PROFIT_PRICE_OF_BUYER = "profitPriceOfBuyer";
        public const string ITEM_ORIGINAL_QUANTITY = "itemOriginalQuantity";
        public const string ADD_COMPANY_FORM = "AddCompanyForm";
        public const string DELETE_COMPANY_FORM = "DeleteCompanyForm";
        public const string UPDATE_COMPANY_FORM = "UpdateCompanyForm";
        public const string INVOICE_NUMBER = "invoiceNumber";
        public const string UPDATE_BUYER_FORM = "updateBuyerForm";
        public const string DELETE_ITEM_FORM = "DeleteItemForm";
        public const string DELETE_BUYER_FORM = "deleteBuyerForm";
        public const string ADD_BUYER_FORM = "AddBuyerForm";
        public const string USER_NAME = "UserName";
        public const string NAME = "Name";
        public const string RECIEPT_ID = "RecieptID";
        public const string CartID = "CartID";
        public const string MERCHANDISER_ID = "MerchandiserID";
        public const string MERCHANDISER_NAME = "MerchandiserName";
        public const string ITEMID_BUYERID_NOT_GIVEN_MESSAGE = "ItemID Or BuyerID Is Not Given..";
        public const string PASSWORD = "Password";
        public const string SOLD_DATE = "SoldDate";
        public const string EMAIL = "Email";
        public const string MYEMAIL = "minhala9@gmail.com";
        public const string MYPASSWORD = "programmer72ubit";
        public const string SMT_GMAIL_COM = "smtp.gmail.com";
        public const string SUBJECT = "Shopping Reciept";
        public const string DOTEDLINE = "---";
        public const string HASCONTAINSTATEMENT = "Has Contain Only";
        public const string RECIEPTGENERATIONMESSAGE = "Reciept is generated";
        public const string FILEPATH = "C:\\Users\\MINHAL\\Desktop\\";
        public const string PDFEXTENSION = ".pdf";
        public const string SNDMAILMESSAGE = "mail Send";
        public const string PIECESINSTOCK = "Pieces in Stock";
        public const string PCUSTOMERID = "pCustomerID";
        public const string PMERCHANDISERNAME = "pMerchandiserName";
        public const string PRECIEPTID = "pRecieptID";
        public const string PDATE= "pDate";
        public const string PTOTAL = "pTotal";
        public const string NULL_STRING = "";
        public const string FILL_ALL_FIELDS = "Please Fill All The Fields";
        public const string WRONG_EMAIL_PASSWORD = "Wrong username/password";
        public const string SIGNUP_REQUEST_SUCCESS= "Your are successfully signUp";
        public const string SIGNUP_REQUEST_FAILED = "Your SignUp Request is failed";
        public const string ID_EXIST = "This ID Is Already Exist";
        public const string ITEM_ID = "ItemID";
        public const string ITEM_NAME = "ItemName";
        public const string COST = "Cost";
        public const string QUANTITY = "Quantity";
        public const string COMPANY_ID = "CompanyID";
        public const string BUYER_ID = "BuyerID";
        public const string BUYER_NAME = "BuyerName";
        public const string BUYER_TYPE = "BuyerType";
        public const string COMPANY_NAME="CompanyName";
        public const string RETAILER = "Retailer";
        public const string WHOLESALLER = "WholeSaller";
        public const string BUYER_EMAIL = "BuyerEmail";
        public const string RETAILER_PROFIT_PRICE = "RetailerProfitPrice";
        public const string WHOLE_SALLER_PROFIT_PRICE = "WholeSallerProfitPrice";
        public const string NULL_PASSWORD = "NULL";
        public const string ITEM_REGISTRATION_TIME = "ItemRegistrationTime";
        public const string COMPANY_REGISTRATION_TIME = "CompanyRegistrationTime";
        public const string BUYER_REGISTRATION_TIME = "BuyerRegistrationTime";
        public const string ADD_ITEM_REQUEST_SUCCESS = "Item Has Been Successfully Added";
        public const string ADD_ITEM_REQUEST_FAIL = "Your Adding Item Request Is Failed";
        public const string UPDATE_ITEM_REQUEST_SUCCESS = "Item Has Been Successfully Updated";
        public const string UPDATE_ITEM_REQUEST_FAIL = "Your Updating Item Request Is Failed";
        public const string DELETE_ITEM_REQUEST_FAIL = "Your Delete Item Request Is Failed";
        public const string DELETE_ITEM_REQUEST_SUCCESS = "Item Has Been Successfully Deleted";
        public const string ADD_COMPANY_REQUEST_SUCCESS = "Company Has Been Successfully Added";
        public const string ADD_COMPANY_REQUEST_FAIL = "Your Adding Company Request Is Failed";
        public const string UPDATE_COMPANY_REQUEST_SUCCESS = "Company Has Been Successfully Updated";
        public const string UPDATE_COMPANY_REQUEST_FAIL = "Your Updating Company Request Is Failed";
        public const string DELETE_COMPANY_REQUEST_SUCCESS = "Company Has Been Successfully Deleted";
        public const string DELETE_COMPANY_REQUEST_FAIL = "Your Deleting Company Request Is Failed";
        public const string ADD_BUYER_REQUEST_SUCCESS = "Buyer Has Been Successfully Added";
        public const string ADD_BUYER_REQUEST_FAIL = "Your Adding Buyer Request Is Failed";
        public const string UPDATE_BUYER_REQUEST_SUCCESS = "Buyer Has Been Successfully Updated";
        public const string UPDATE_BUYER_REQUEST_FAIL = "Your Update Buyer Request Is Failed";
        public const string DELETE_BUYER_REQUEST_SUCCESS = "Buyer Has Been Successfully Deleted";
        public const string DELETE_BUYER_REQUEST_FAIL = "Your Deleted Buyer Request Is Failed";
        public const string CART_FORM = "CartForm";
        public const string SELECT_BUYER_FORM = "SelectBuyerForm";
        public const string AMOUNT = "Amount";
        public const string TOTAL_AMOUNT = "TotalAmount";
        public const string UNIT_PRICE = "UnitPrice";
        public const string CART_MESSAGE = "Cart Has Been Successfully Saved";
    }
}
